//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingZone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Products()
        {
            this.tbl_order = new HashSet<tbl_order>();
        }

        public int ProdId { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Product Name")]
        public string ProdName { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Description")]
        public string ProdDesc { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public Nullable<int> Price { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string Image { get; set; }
        public Nullable<int> CatId { get; set; }

        public virtual tbl_Categories tbl_Categories { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order> tbl_order { get; set; }
    }
}
